module.exports.phishingKeywords = [
    // Urgent Actions
    "urgent", "immediate action required", "act now", "do not ignore", "final notice",
    "last chance", "act fast", "act immediately", "urgent response", "final warning",
    "final attempt", "critical alert", "last opportunity", "respond now", "quick action required",
    "emergency request", "act before it's too late", "high-priority notice", "immediate review required",

    // Account Verification and Security Alerts
    "verify your account", "confirm your identity", "account verification needed",
    "validate your account", "account locked", "account frozen", "account compromised",
    "unauthorized access detected", "suspicious activity detected", "security alert",
    "critical security update", "security breach", "your account is at risk",
    "account suspension notice", "account will be deactivated", "account review required",
    "account alert", "critical account update", "account risk notification", "immediate account verification",
    "reset your security questions", "update security settings", "your account is compromised",
    "safety alert", "emergency account alert", "account security upgrade", "sensitive account issue",
    "protect your account", "email quota exceeded", "unusual login attempt", "unrecognized device login",
    "unusual account activity", "restricted account", "compromised account",

    // Passwords and Login Details
    "password reset", "reset your password", "change your password", "password expired",
    "login immediately", "verify login credentials", "confirm login details",
    "email authentication needed", "update login information", "your password expired",
    "reset password now", "confirm password", "your login attempt failed", "password change required",
    "login verification required", "unauthorized password reset", "security question update required",

    // **Bank & Financial Details**
    "bank account verification", "verify bank details", "confirm banking information",
    "your bank details needed", "update your bank details", "bank fraud alert",
    "unusual transaction detected", "credit card update", "loan approved",
    "secure your funds", "unauthorized withdrawal", "financial compensation",
    "credit score update", "tax refund available", "credit report anomaly",
    "wire transfer request", "withdrawal request", "ATM withdrawal alert",
    "direct deposit alert", "overdue loan payment", "auto loan update",
    "insurance claim payout", "unrecognized bank charge", "bounced check alert",
    "loan forgiveness program", "credit limit increase", "pre-approved credit card",
    "unpaid dues notice", "unauthorized loan application", "suspicious financial activity",
    "government stimulus payment", "unexpected wire transfer", "pending loan approval",
    "verify tax details", "pending tax refund", "confirm banking PIN", 
    "your mortgage has been updated", "fake bank communication", "ACH payment alert",
    "wire fraud detected", "investment scam warning", "fraudulent stock purchase detected",
    "suspicious cryptocurrency transaction", "bitcoin payment required",
    "update online banking password", "bank OTP required", "pending credit card payment",
    "foreign bank transaction detected", "your financial details needed",
    "funds locked, verify identity", "credit card breach alert", "unauthorized cash advance",
    "debit card alert", "flagged credit transaction", "suspicious escrow payment",
    "high-risk transaction detected", "invest now for high returns", "forex trading scam",
    "immediate funds transfer", "block suspicious transaction", "high-return investment opportunity",

    // **Personal Details & Identity Theft**
    "confirm personal information", "verify identity", "government-issued ID required",
    "update social security details", "your social security number is compromised",
    "verify your social security number", "identity theft alert", "your national ID has been used",
    "sensitive personal data required", "confidential information request", 
    "your driver's license is required", "upload passport details", "proof of address required",
    "background check request", "criminal background alert", "confirm your mother's maiden name",
    "identity verification required", "upload KYC documents", "fraudulent tax filing detected",
    "your Aadhaar card needs verification", "national insurance scam alert",
    "student loan scam alert", "passport control notification", "check your criminal record",
    "your ID was used fraudulently", "pending identity confirmation",
    "biometric authentication required", "sensitive document upload required",
    "verify employment records", "confirm residency status", "your SSN has been flagged",
    "identity fraud warning", "confirm marital status", "police background check",
    "government ID revalidation", "your credit history report is suspicious",
    "data breach involving your details", "fake background check request",

    // Billing and Payment-Related
    "request for payment", "confirm your payment", "verify billing information",
    "billing issue", "account validation", "payment overdue", "refund issued",
    "confirm transaction", "transaction declined", "transaction failure", "confirm purchase",
    "unauthorized withdrawal", "money transfer", "wire transfer request",
    "withdrawal request", "payment confirmation required", "overdue balance", "overdue invoice",
    "secure online payment", "double charge refund", "billing adjustment required",
    "fraudulent billing notification", "fake invoice", "unauthorized service charge",

    // Promotions and Prizes
    "you have won", "lottery winner", "claim your prize", "sweepstakes winner",
    "redeem now", "redeem gift card", "double your money", "earn money fast",
    "make money online", "investment opportunity", "crypto investment", "free bitcoin",
    "free trial", "bonus credit", "cashback offer", "free gift", "giveaway",
    "limited time offer", "exclusive deal", "big discount", "best deal",
    "special promotion", "VIP access", "instant cash reward", "scratch and win",
    "get rich quick", "easy money", "hot stock tip", "fast approval", "guaranteed income",
    "increase credit limit", "limited availability", "free membership upgrade",
    "low interest loan", "zero interest financing", "free shopping spree",
    "insider stock tip", "VIP rewards program", "one-time bonus opportunity",

    // Government or Authoritative Messages
    "government notice", "IRS notice", "police report", "official notification",
    "federal alert", "court summons", "tax audit", "social security update",
    "health insurance update", "medical benefits", "social security fraud alert",
    "fake government communication", "police subpoena", "federal investigation",
    "background check required", "fraud alert from law enforcement", "criminal record update",
    "warrant issued in your name", "immigration alert", "visa approval confirmation",
    "embassy clearance required", "your national insurance number is flagged",
    "CCTV footage request", "homeland security warning", "pending legal action",
    "court settlement offer", "your identity has been stolen", "legal complaint against you",

    // Miscellaneous Red Flags
    "click here", "download required", "remote access request", "customer support",
    "CEO request", "confidential message", "risk detected", "investment tip",
    "phishing attempt detected", "bank fraud prevention", "lost package claim",
    "your email has been flagged", "urgent compliance notice",
    "anonymous complaint filed", "security breach investigation",
    "your privacy settings need updating", "new service agreement",
    "corporate policy change", "restricted access", "your order is delayed",
    "fake support ticket", "suspicious help desk request",
  "act now to prevent security breach",
  "confirm action before deadline",
  "unauthorized request detected",
  "risk alert: respond immediately",
  "emergency action required",
  "urgent verification process",
  "respond before system restriction",
  "critical notification: take action",
  "prevent loss by verifying now",
  "alert: time-sensitive issue detected",
  "confirm response before closure",
  "security risk: verify identity",
  "last warning before suspension",
  "confirm details before access lock",
  "security flag: immediate review",
  "update required to avoid service disruption",
  "restricted function: confirm access",
  "verify data before removal",
  "prevent service suspension now",
  "urgent access request confirmation",
  "confirm security status immediately",
  "emergency system update needed",
  "immediate response required for security",
  "prevent unauthorized action by confirming",
  "alert: verify before it's too late",
  "verify identity to retain access",
  "confirm security check before lockout",
  "unusual login attempt detected",
  "urgent: unauthorized login detected",
  "confirm ownership of your credentials",
  "alert: multiple failed login attempts",
  "protect account before breach occurs",
  "new login activity needs review",
  "review security alert immediately",
  "account flagged for suspicious activity",
  "unknown access attempt requires confirmation",
  "reset security settings for account protection",
  "verify security settings update",
  "unauthorized session detected, secure account",
  "confirm login attempt from new device",
  "prevent access issues with security check",
  "review security logs for unusual activity",
  "two-factor authentication required now",
  "potential identity fraud alert",
  "security lockout in progress, verify identity",
  "alert: security update required",
  "confirm account authenticity now",
  "security policy violation warning",
  "reverify your security details",
  "suspicious attempt to modify account detected",
  "verify recent password change request",
  "update password to prevent compromise",
  "unexpected login attempt detected",
  "confirm new authentication method",
  "login credentials flagged for review",
  "reset authentication to avoid lockout",
  "new login location detected, verify",
  "warning: password security breach risk",
  "confirm account access through password check",
  "failed password entry detected",
  "recent login unusual, confirm identity",
  "multi-factor authentication required",
  "reauthenticate password credentials",
  "alert: confirm password reset request",
  "verify saved login details for security",
  "update old password for security compliance",
  "unknown login pattern detected",
  "protect access with a strong password update",
  "verify identity before password update",
  "confirm email and password combination",
  "alert: suspicious login attempt detected",
  "prevent lockout by resetting password",
  "update credentials for enhanced security",
  "unauthorized login flagged for review",
  "confirm new device access request",
  "verify financial activity now",
  "alert: unknown transaction detected",
  "urgent action required: financial review",
  "security risk: unverified banking activity",
  "confirm payment authorization",
  "alert: bank account irregularity",
  "unknown transaction flagged for fraud",
  "suspicious account activity detected",
  "prevent fraudulent withdrawal",
  "update security details for account safety",
  "alert: payment processing issue",
  "verify withdrawal request",
  "review suspicious credit transaction",
  "unauthorized debit card usage detected",
  "confirm transaction before approval",
  "financial alert: account lock warning",
  "fraudulent banking attempt blocked",
  "confirm details for pending transaction",
  "unusual spending pattern detected",
  "verify banking credentials to continue",
  "unauthorized financial access alert",
  "urgent: unexpected funds transfer detected",
  "warning: unauthorized billing access",
  "action needed: verify banking compliance",
  "confirm large purchase authorization",
  "prevent fraudulent charge on account",
  "unexpected charge alert: review now",
  "verify recurring payment details",
  "unknown auto-renewal detected",
  "secure your billing details now",
  "suspicious refund request alert",
  "review unexpected fee application",
  "unauthorized transaction flagged",
  "alert: unknown payment request",
  "confirm recent charge for security",
  "unauthorized subscription attempt detected",
  "pending payment review required",
  "payment credentials flagged for security",
  "protect account from billing fraud",
  "unexpected billing update detected",
  "confirm refund request for processing",
  "review unrecognized charge now",
  "warning: excessive payment attempts",
  "alert: unknown credit card activity",
  "verify details for recent subscription renewal",
  "suspicious invoice detected, review required",
  "update payment method to avoid disruption",
  "alert: billing access attempt detected",
  "confirm purchase before processing",
  "review automatic charge settings",
  "confirm access to premium membership",
  "upgrade now to secure benefits",
  "alert: limited-time service promotion",
  "review VIP upgrade offer",
  "confirm eligibility for exclusive membership",
  "unlock additional features today",
  "prevent downgrade by confirming subscription",
  "verify special offer details",
  "limited slots available for priority access",
  "premium account trial ending soon",
  "last chance to retain benefits",
  "confirm access to promotional deal",
  "alert: promotional membership expiring",
  "new service enhancements available",
  "exclusive feature rollout for select users",
  "act now to keep premium status",
  "warning: service access restriction pending",
  "register for extended premium access",
  "free trial renewal option available",
  "VIP access renewal required",
  "limited-time enhancement activation available",
  "secure special benefits before expiration",
  "exclusive invitation to upgrade service",
  "confirm continued premium subscription",
  "priority support access expiring soon",
  "exclusive prize available for claim",
  "confirm bonus reward selection",
  "final chance to claim sweepstakes prize",
  "special contest opportunity pending",
  "alert: unclaimed free reward",
  "confirm eligibility for grand prize",
  "complete entry to win instant reward",
  "exclusive loyalty reward confirmation",
  "limited-time mystery giveaway",
  "urgent: confirm participation in contest",
  "secure bonus prize before expiration",
  "verify surprise gift selection",
  "unlock special raffle draw prize",
  "exclusive VIP giveaway access",
  "confirm details for prize delivery",
  "instant redemption required for giveaway",
  "last call: unclaimed contest reward",
  "limited entries left for exclusive sweepstakes",
  "validate participation in bonus giveaway",
  "warning: giveaway access expiring soon",
  "confirm prize status before it’s lost",
  "urgent: check eligibility for jackpot prize",
  "act now to redeem your special reward",
  "final confirmation needed for contest prize",
  "special access granted for reward claim",
  "urgent: system performance risk detected",
  "warning: unauthorized software detected",
  "review software security settings",
  "alert: malware scan required",
  "unknown system process detected",
  "verify system security protocol",
  "security patch missing, update required",
  "critical vulnerability detected in software",
  "confirm software update installation",
  "unauthorized script running in background",
  "immediate review needed for software security",
  "alert: unknown access attempt detected",
  "update firewall settings for protection",
  "confirm device security scan",
  "alert: software protection expired",
  "unauthorized registry modification detected",
  "critical software defense update needed",
  "security breach attempt detected",
  "verify firewall settings for maximum security",
  "alert: unknown process modifying system files",
  "prevent potential exploit with update",
  "alert: security monitoring tool detected issue",
  "review antivirus settings for optimal protection",
  "verify installation of latest security patch",
  "warning: detected attempt to access system remotely",
  "critical action needed", "immediate risk alert", "respond without delay",
  "urgent compliance issue", "emergency security update", "high-severity incident",
  "system at critical risk", "immediate user verification", "crucial response required",
  "don't lose your account", "urgent threat detected", "emergency intervention needed",
  "respond now to prevent issues", "limited-time resolution window", "failure to act will cause loss",
  "only 24 hours left to act", "critical update available", "immediate system patch required",
  "verify before deadline expires", "irreversible action pending", "confirm before suspension",
  "high-alert notification", "urgent legal action required", "prevent irreversible lockout",
  "sensitive data exposure risk",
  "reauthenticate your account", "warning: security protocol update", "protect your login credentials",
  "new login from flagged location", "identity mismatch detected", "unusual admin request detected",
  "complete security validation", "recent security settings change", "forced logout due to policy change",
  "confirm device synchronization", "safety check: verify account activity", "login freeze due to anomaly",
  "validate your profile credentials", "restricted login session detected", "ensure compliance with security policies",
  "verify ownership of this account", "unknown security token detected", "login recovery process initiated",
  "confirm your account is still active", "firewall detected unusual traffic", "required authentication check",
  "urgent security code request", "system security verification pending", "suspicious app access detected",
  "authentication delay warning",
  "multi-step verification needed", "confirm your new login method", "security token expired, renew now",
  "verify your password history", "login reset required for continued access", "password risk assessment needed",
  "unknown access attempt blocked", "new password requirement update", "delayed authentication warning",
  "confirm your new login credentials", "identity challenge question failed", "unknown email linked to your account",
  "outdated password detected, change now", "failed login pattern detected", "log out from all sessions for safety",
  "password synchronization required", "new access attempt via unauthorized device", "additional authentication required",
  "reset access control settings", "challenge authentication failed", "recent login revoked due to risk",
  "re-enable access via secure link", "verify trusted device registration", "alert: reset your password for security",
  "secure your access with an updated password",
  "urgent fraud prevention check", "review suspicious financial activity", "confirm large transaction authorization",
  "new transaction flagged for review", "verify unusual withdrawal attempt", "account temporarily locked due to financial risk",
  "confirm recent cash transfer", "abnormal purchase detected", "incorrect banking credentials entered",
  "suspicious auto-payment setup detected", "action required: validate new transaction", "verify your savings balance urgently",
  "secure your banking session", "alert: foreign transaction detected", "confirm your bank card activation",
  "transaction denial warning", "prevent payment processing failure", "alert: suspicious banking API access",
  "emergency account hold initiated", "unauthorized merchant transaction flagged", "update your card security preferences",
  "urgent notice: compromised bank details", "unauthorized transaction prevention update", "mandatory compliance verification",
  "ensure account details are current", "high-value transaction confirmation needed",
  "update billing preferences immediately", "confirm payment method before expiration", "unexpected service fee applied",
  "alert: unauthorized subscription renewal", "fake chargeback dispute detected", "merchant refund delay warning",
  "avoid unexpected billing charges", "account at risk: confirm payment info", "pending invoice review required",
  "alert: fake discount applied to your purchase", "verify refund claim details", "renew your subscription to avoid disruption",
  "payment credentials outdated, update now", "warning: excessive refund claims detected", "verify cardholder identity for transaction",
  "secure checkout error detected", "confirm billing address update", "fake promo code detected",
  "action required: review past transactions", "validate recent order confirmation", "unprocessed refund notification",
  "fraudulent e-commerce transaction flagged", "validate mobile wallet security settings", "review and update auto-payment rules",
  "unexpected credit adjustment applied",
  "free trial expiring, confirm renewal", "exclusive membership bonus expiring", "urgent: claim your limited-time offer",
  "confirm eligibility for VIP access", "alert: exclusive deal expiring soon", "register now for your bonus package",
  "congratulations! unlock your exclusive reward", "free shipping offer expiring soon", "urgent: confirm limited-time service upgrade",
  "act now: premium access at no cost", "last chance to redeem your loyalty points", "alert: promotional discount ending soon",
  "warning: unauthorized use of discount code", "confirm premium status before expiration", "limited membership extension offer",
  "review additional benefits before loss", "complimentary service expiring soon", "exclusive beta access requires confirmation",
  "urgent: special upgrade pricing available", "warning: promotional period ending", "new service enhancements available",
  "confirm eligibility for premium perks", "high-priority early access opportunity", "complete your registration for extra benefits",
  "discount code misapplied, review transaction",
  "you have been selected as a winner!", "confirm your free prize claim now", "alert: giveaway reward pending",
  "urgent: confirm shipping for your prize", "congratulations! verify reward redemption", "confirm eligibility for sweepstakes bonus",
  "claim your contest reward before expiration", "winner selection notice, respond now", "secure your raffle prize",
  "your exclusive gift is waiting", "final call: claim your prize today", "unclaimed reward, verify to receive",
  "urgent: confirm lucky draw winnings", "bonus points available for redemption", "complete survey to access prize",
  "you have a pending contest entry", "verify promotional giveaway eligibility", "exclusive access to premium sweepstakes",
  "congratulations! your reward is ready", "unclaimed bonus, act before expiry", "instant reward confirmation required",
  "mystery prize revealed, claim now", "surprise reward pending verification", "redeem your prize with verification code",
  "exclusive participation reward confirmation",
  "alert: device security compromised", "critical software patch required", "system at risk, update now",
  "confirm antivirus protection settings", "fake security certificate detected", "unauthorized software installation detected",
  "urgent: update your system firewall", "warning: device at risk of malware attack", "confirm software license renewal",
  "unknown app detected, review access", "unauthorized app installation attempt", "verify system security configuration",
  "suspicious process running in background", "action required: review antivirus alerts", "forced update required for system stability",
  "confirm driver update for compatibility", "fake tech support request detected", "system breach attempt prevented",
  "unknown script execution flagged", "unauthorized system update attempt", "critical patch required for device safety",
  "review and approve software installation", "system shutdown imminent without update", "network security breach warning",
  "time-critical security fix",
  "high-alert emergency case",
  "unauthorized escalation warning",
  "respond before system breach",
  "critical failure detected",
  "complete this action immediately",
  "final attempt before closure",
  "your access will be revoked soon",
  "security deadline approaching",
  "unauthorized modification detected",
  "failure to respond will result in loss",
  "restricted access warning",
  "emergency user verification required",
  "last-minute account review",
  "respond to prevent access loss",
  "high-risk policy violation",
  "potential security lapse detected",
  "urgent confirmation needed",
  "time-sensitive review required",
  "action needed before full restriction",
  "account flagged for inactivity",
  "confirm to prevent shutdown",
  "unauthorized setting change detected",
  "complete compliance check now",
  "irreversible lockout pending",
  "forced logout due to security breach",
  "unrecognized network login detected",
  "confirm recent account modification",
  "identity authentication required",
  "security key mismatch warning",
  "critical identity check needed",
  "alert: suspicious account reactivation",
  "immediate security settings review",
  "verify new user session",
  "authentication mismatch flagged",
  "update your credentials to continue",
  "immediate access validation required",
  "your account is under review",
  "unauthorized software accessing your account",
  "sensitive data exposure warning",
  "email re-verification required",
  "unauthorized email settings change",
  "confirm this login before continuing",
  "ensure account security compliance",
  "new login attempt under scrutiny",
  "security access level modified",
  "password recovery email requested",
  "suspicious behavior detected in account",
  "unknown device attempting access",
  "critical notification: update security settings",
  "reset login method immediately",
  "unknown authentication challenge detected",
  "password expiration warning",
  "update password for continued access",
  "security PIN required to proceed",
  "invalid credentials detected, change password",
  "unauthorized access attempt flagged",
  "confirm updated security questions",
  "login authentication error detected",
  "secure your login with a new passcode",
  "forced password reset required",
  "unauthorized password update attempt",
  "compromised credentials warning",
  "confirm updated login requirements",
  "password validation request pending",
  "unauthorized login detected from flagged IP",
  "expired authentication token detected",
  "suspicious multi-factor authentication attempt",
  "password recovery process incomplete",
  "prevent unauthorized login with update",
  "secure access by changing credentials",
  "challenge question verification failed",
  "authentication lockout warning",
  "alert: weak password detected",
  "unexpected password change request",
  "unauthorized wire transfer attempt detected",
  "unexpected debit card transaction flagged",
  "fraudulent check deposit alert",
  "confirm transaction before bank hold",
  "alert: unverified loan application",
  "unknown cash withdrawal attempt",
  "restricted funds access warning",
  "confirm before bank account lock",
  "unauthorized foreign transaction detected",
  "suspicious banking credentials change",
  "confirm suspicious financial behavior",
  "alert: possible identity theft in bank account",
  "delayed bank authorization alert",
  "overdraft alert: confirm deposit",
  "unrecognized credit transaction pending",
  "security flag on recent bank deposit",
  "update banking verification details",
  "new banking rule compliance required",
  "verify third-party access to funds",
  "fraudulent e-wallet transfer flagged",
  "potential fraud detected on account",
  "unauthorized financial modification warning",
  "recent high-value purchase flagged",
  "high-risk banking transaction alert",
  "confirm loan repayment details",
  "unexpected charge on billing statement",
  "unauthorized renewal payment processed",
  "alert: disputed payment issue",
  "fraudulent merchant payment alert",
  "update payment card for billing accuracy",
  "unauthorized subscription payment initiated",
  "auto-payment authorization pending",
  "confirm billing verification request",
  "subscription renewal notice – urgent",
  "unauthorized refund request alert",
  "confirm recent payment adjustment",
  "warning: refund request not verified",
  "delayed billing cycle issue detected",
  "refund transaction flagged for security",
  "prevent subscription deactivation now",
  "review your billing history for errors",
  "unusual chargeback request detected",
  "subscription downgrade warning",
  "verify premium account payment",
  "confirm saved payment method security",
  "pending service payment issue",
  "invoice discrepancy detected",
  "fake discount code applied, review order",
  "unexpected vendor charge alert",
  "update billing cycle preferences",
  "upgrade now to avoid service loss",
  "alert: last chance for VIP access",
  "exclusive offer for select users only",
  "confirm eligibility for extended service",
  "warning: special pricing expires soon",
  "unlock your premium service now",
  "verify upgraded features activation",
  "confirm access to limited service package",
  "redeem your one-time offer today",
  "upgrade to avoid disruption",
  "free trial extension available",
  "last-minute deal verification needed",
  "premium content access expiring",
  "verify VIP membership perks",
  "urgent notice: final service upgrade",
  "confirm priority status update",
  "prevent downgrade to basic plan",
  "one-time offer available for activation",
  "limited promotional access expiring soon",
  "review your premium benefits before expiration",
  "exclusive early-access membership invite",
  "priority customer access pending verification",
  "confirm your eligibility for additional perks",
  "urgent service upgrade deadline approaching",
  "verify subscription package selection",
  "congratulations! claim your exclusive prize",
  "confirm eligibility for special lottery",
  "urgent: verify free gift selection",
  "limited-time reward pending confirmation",
  "mystery bonus available for instant claim",
  "alert: prize expiration warning",
  "enter now for an exclusive giveaway",
  "confirm participation for instant reward",
  "urgent: contest winner verification",
  "final notice: unclaimed prize waiting",
  "last step before prize redemption",
  "complete the process to unlock bonus",
  "your giveaway reward expires soon",
  "claim loyalty reward before expiration",
  "sweepstakes entry requires confirmation",
  "bonus giveaway for verified users only",
  "unlock your VIP giveaway prize",
  "confirm participation to win free rewards",
  "act fast: limited contest spots available",
  "secure your winning entry today",
  "mystery sweepstakes result pending",
  "verify eligibility for contest prize",
  "time-sensitive bonus waiting for you",
  "confirm exclusive raffle draw entry",
  "exclusive reward selection confirmation",
  "warning: device performance compromised",
  "critical software update required immediately",
  "suspicious script running on device",
  "security risk: unauthorized software detected",
  "fake tech support request flagged",
  "immediate update required for malware protection",
  "alert: system memory corruption detected",
  "unauthorized system configuration change detected",
  "software license expiration warning",
  "confirm download of urgent security patch",
  "system scan required for threat detection",
  "remote access request detected on your system",
  "confirm installation of recommended security update",
  "immediate system check required for stability",
  "critical error: software failure detected",
  "security warning: outdated driver detected",
  "tech support scam detected, verify source",
  "fake customer service chat detected",
  "unauthorized software execution attempt",
  "malicious activity detected on your device",
  "unknown access to system settings",
  "security certificate invalid, update required",
  "alert: unauthorized IP attempting remote access",
  "confirm identity before troubleshooting request",
  "unauthorized access to hardware detected"
];
