module.exports.phishingKeywords = [
    // Urgent Actions
    "urgent", "immediate action required", "act now", "do not ignore", "final notice",
    "last chance", "act fast", "act immediately", "urgent response", "final warning",
    "final attempt", "critical alert", "last opportunity", "respond now", "quick action required",
    "emergency request", "act before it's too late", "high-priority notice", "immediate review required",

    // Account Verification and Security Alerts
    "verify your account", "confirm your identity", "account verification needed",
    "validate your account", "account locked", "account frozen", "account compromised",
    "unauthorized access detected", "suspicious activity detected", "security alert",
    "critical security update", "security breach", "your account is at risk",
    "account suspension notice", "account will be deactivated", "account review required",
    "account alert", "critical account update", "account risk notification", "immediate account verification",
    "reset your security questions", "update security settings", "your account is compromised",
    "safety alert", "emergency account alert", "account security upgrade", "sensitive account issue",
    "protect your account", "email quota exceeded", "unusual login attempt", "unrecognized device login",
    "unusual account activity", "restricted account", "compromised account",

    // Passwords and Login Details
    "password reset", "reset your password", "change your password", "password expired",
    "login immediately", "verify login credentials", "confirm login details",
    "email authentication needed", "update login information", "your password expired",
    "reset password now", "confirm password", "your login attempt failed", "password change required",
    "login verification required", "unauthorized password reset", "security question update required",

    // **Bank & Financial Details**
    "bank account verification", "verify bank details", "confirm banking information",
    "your bank details needed", "update your bank details", "bank fraud alert",
    "unusual transaction detected", "credit card update", "loan approved",
    "secure your funds", "unauthorized withdrawal", "financial compensation",
    "credit score update", "tax refund available", "credit report anomaly",
    "wire transfer request", "withdrawal request", "ATM withdrawal alert",
    "direct deposit alert", "overdue loan payment", "auto loan update",
    "insurance claim payout", "unrecognized bank charge", "bounced check alert",
    "loan forgiveness program", "credit limit increase", "pre-approved credit card",
    "unpaid dues notice", "unauthorized loan application", "suspicious financial activity",
    "government stimulus payment", "unexpected wire transfer", "pending loan approval",
    "verify tax details", "pending tax refund", "confirm banking PIN", 
    "your mortgage has been updated", "fake bank communication", "ACH payment alert",
    "wire fraud detected", "investment scam warning", "fraudulent stock purchase detected",
    "suspicious cryptocurrency transaction", "bitcoin payment required",
    "update online banking password", "bank OTP required", "pending credit card payment",
    "foreign bank transaction detected", "your financial details needed",
    "funds locked, verify identity", "credit card breach alert", "unauthorized cash advance",
    "debit card alert", "flagged credit transaction", "suspicious escrow payment",
    "high-risk transaction detected", "invest now for high returns", "forex trading scam",
    "immediate funds transfer", "block suspicious transaction", "high-return investment opportunity",

    // **Personal Details & Identity Theft**
    "confirm personal information", "verify identity", "government-issued ID required",
    "update social security details", "your social security number is compromised",
    "verify your social security number", "identity theft alert", "your national ID has been used",
    "sensitive personal data required", "confidential information request", 
    "your driver's license is required", "upload passport details", "proof of address required",
    "background check request", "criminal background alert", "confirm your mother's maiden name",
    "identity verification required", "upload KYC documents", "fraudulent tax filing detected",
    "your Aadhaar card needs verification", "national insurance scam alert",
    "student loan scam alert", "passport control notification", "check your criminal record",
    "your ID was used fraudulently", "pending identity confirmation",
    "biometric authentication required", "sensitive document upload required",
    "verify employment records", "confirm residency status", "your SSN has been flagged",
    "identity fraud warning", "confirm marital status", "police background check",
    "government ID revalidation", "your credit history report is suspicious",
    "data breach involving your details", "fake background check request",

    // Billing and Payment-Related
    "request for payment", "confirm your payment", "verify billing information",
    "billing issue", "account validation", "payment overdue", "refund issued",
    "confirm transaction", "transaction declined", "transaction failure", "confirm purchase",
    "unauthorized withdrawal", "money transfer", "wire transfer request",
    "withdrawal request", "payment confirmation required", "overdue balance", "overdue invoice",
    "secure online payment", "double charge refund", "billing adjustment required",
    "fraudulent billing notification", "fake invoice", "unauthorized service charge",

    // Promotions and Prizes
    "you have won", "lottery winner", "claim your prize", "sweepstakes winner",
    "redeem now", "redeem gift card", "double your money", "earn money fast",
    "make money online", "investment opportunity", "crypto investment", "free bitcoin",
    "free trial", "bonus credit", "cashback offer", "free gift", "giveaway",
    "limited time offer", "exclusive deal", "big discount", "best deal",
    "special promotion", "VIP access", "instant cash reward", "scratch and win",
    "get rich quick", "easy money", "hot stock tip", "fast approval", "guaranteed income",
    "increase credit limit", "limited availability", "free membership upgrade",
    "low interest loan", "zero interest financing", "free shopping spree",
    "insider stock tip", "VIP rewards program", "one-time bonus opportunity",

    // Government or Authoritative Messages
    "government notice", "IRS notice", "police report", "official notification",
    "federal alert", "court summons", "tax audit", "social security update",
    "health insurance update", "medical benefits", "social security fraud alert",
    "fake government communication", "police subpoena", "federal investigation",
    "background check required", "fraud alert from law enforcement", "criminal record update",
    "warrant issued in your name", "immigration alert", "visa approval confirmation",
    "embassy clearance required", "your national insurance number is flagged",
    "CCTV footage request", "homeland security warning", "pending legal action",
    "court settlement offer", "your identity has been stolen", "legal complaint against you",

    // Miscellaneous Red Flags
    "click here", "download required", "remote access request", "customer support",
    "CEO request", "confidential message", "risk detected", "investment tip",
    "phishing attempt detected", "bank fraud prevention", "lost package claim",
    "your email has been flagged", "urgent compliance notice",
    "anonymous complaint filed", "security breach investigation",
    "your privacy settings need updating", "new service agreement",
    "corporate policy change", "restricted access", "your order is delayed",
    "fake support ticket", "suspicious help desk request"
];
