module.exports.phishingKeywords=[
    "urgent", "verify your account", "update your information", "security alert",
    "password reset", "click here", "limited time offer", "suspicious activity detected",
    "confirm your identity", "you have won", "lottery winner", "claim your prize",
    "login immediately", "bank account verification", "fraud alert", "paypal security",
    "free bitcoin", "crypto scam", "CEO request", "urgent response", "overdue balance",
    "unusual login attempt", "social security update", "IRS notice", "fake invoice",
    "identity theft", "refund issued", "banned account warning", "download required",
    "reset password now", "act fast", "final notice", "restricted account", "customer support",
    "confirm password", "billing issue", "compromised account", "dispute resolution",
    "online banking access", "risk detected", "unauthorized transaction", "final warning",
    "transaction failure", "account validation", "unblock your account", "insurance claim",
    "money transfer", "request for payment", "email verification", "free gift", "cashback offer",
    "double your money", "sign in now", "warning message", "transaction declined",
    "fake email", "government notice", "police report", "access denied", "your password expired",
    "upgrade required", "email quota exceeded", "package delivery failure", "confirm transaction",
    "security breach", "protect your account", "access suspended", "sweepstakes winner",
    "complete registration", "login alert", "special promotion", "big discount", "best deal",
    "act now", "giveaway", "you are selected", "earn money fast", "online survey reward",
    "loan approved", "credit card update", "confidential message", "redeem now",
    "act before it's too late", "limited availability", "exclusive offer", "click to claim",
    "verify payment", "your account is at risk", "final attempt", "secure your funds",
    "your account will be deactivated", "last chance", "confirm purchase", "unauthorized withdrawal",
    "financial compensation", "class action settlement", "credit score update", "tax refund available",
    "health insurance update", "medical benefits", "free trial", "bonus credit", "VIP access",
    "crypto investment", "hot stock tip", "easy money", "fast approval", "guaranteed income",
    "increase credit limit", "investment opportunity", "make money online", "no credit check",
    "one-time password", "pay now", "personal data request", "redeem gift card",
    "remote access request", "security system update", "urgent action required",
    "verify ownership", "verify phone number", "verify social security number",
    "wire transfer request", "withdrawal request"
  ];
